sudo: required
dist: trusty

services: [docker]

language: bash

cache:
  directories:
    - $TRAVIS_BUILD_DIR/cache

jobs:
  include:
    - stage: static
      script: travis/run_tests.sh static
    - stage: unit
      script: travis/run_tests.sh unit