sudo: required
dist: trusty

services: [docker]

language: bash

install:
    - pip install --user codecov

cache:
  directories:
    - $TRAVIS_BUILD_DIR/cache

jobs:
  include:
    - stage: static
      script: travis/prep_tests.sh static

after_sucess:
    - codecov