codecov:
  branch: master       # the branch to show by default, inherited from your git repository setting

coverage:
  ignore:          # files and folders that will be removed during processing
    - "ropa/tests/*"